wordlist:
	edictor wordlist --dataset=../cldf/cldf-metadata.json --name=dhakalsouthwesttibetic --preprocess=preprocessing.py

sqlite:
	edictor wordlist --dataset=../cldf/cldf-metadata.json --name=dhakalsouthwesttibetic --preprocess=preprocessing.py --sqlite
